name: "Setup deb-s3"
description: 'Setup deb-s3 in your Github Actions workflow.'
author: Alw3ys

branding:
  icon: 'play-circle'
  color: 'red'

runs:
  using: "composite"
  steps:
    - run: |
        sudo wget -O /etc/apt/trusted.gpg.d/deb-s3-archive-keyring.gpg https://raw.githubusercontent.com/deb-s3/deb-s3/master/deb-s3-archive-keyring.gpg
        echo "deb https://deb-s3-repo.s3.us-east-2.amazonaws.com/$(lsb_release -is | tr A-Z a-z)/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list > /dev/null
        sudo apt-get update
        sudo apt-get install deb-s3
      shell: bash
